### PR TITLE
ICARUS PDS validation trees

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This branch builds upon the modules by @fjnicolas in pull request #29.
It includes:
* an adapter from `sim::SimPhotons` (ICARUS current favourite) to `sim::SimPhotonsLite` (which @fjnicolas job works on)
* a job configuration to run the adapter and the tree maker
* a fix for a problem for ICARUS in one module (inclusion of a SBND header) (which may disappear since I just noticed that I am on code review duty for it)
* it also enables some source tree under `ICARUS`: please check that the stuff I added is in the desired location

The only testing I did was to verify that a couple of branches in the tree is actually filled with numbers. It is!! End of test.
The input file was from a "reco2" simulation file from a recent ICARUS production.

Also note running the configurations in here requires FHiCL configurations (geometry and detector clock services, mainly) which are in `icaruscode`. The current `develop` branch will not set up `icaruscode` (it requires a version that `icaruscode` never had or will have), so I resorted to replacing that version (`v09_32_00`) with a suitable one (`v09_32_01_01`) in the `ups/product_deps` file.

### CODE REVIEW

**Review by chilge — APPROVED** [review]
looks good to me!

**Review by henrylay97 — APPROVED** [review]
I can only really comment on the CI architecture side of things which looks good to me! I'll merge it into the next tag. @vitodb  @chilge are there plans to establishe a `CI_VALIDATION_ICARUS` workflow soon to utilise this?

**Comment by vitodb** [comment]
I'm adding `CI_VALIDATION_ICARUS` workflow in a bit.
For ICARUS CI Validation, it is enough as starting point to build `icaruscode icarusutil sbnci`, similarly to how we do for SBND, or there is the need to build also other ICARUS related repos?

**Comment by PetrilloAtWork** [comment]
Relevant for physics are also `icarusalg` and `icarus_signal_processing` (I hope I got the name right).

**Review by fjnicolas — APPROVED** [review]
The SimPhotons adapter looks good!
Just note that the histogram ranges and number of bins in the PDS PlottingScript may need some tuning for the ICARUS case.

**Pull request merged**
